import { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowUpFromLine, AudioLines, Check, ChevronRight, CircleHelp, Copy, Disc3, FolderOpen, Headphones, Link2, Play, Plus, Radio, Save, Share2, SlidersHorizontal, Square, Trash2, Volume2, Waves, X } from 'lucide-react';
import { AudioEngine } from './audio/engine';
import type { EngineSnapshot, Patch } from './types';
import { PRESETS, applyMacro, copyPreset } from './presets';
import { createShareUrl, deleteSavedPatch, exportPatch, importPatch, listSavedPatches, readSharedPatch, savePatch, type SavedPatch } from './storage';
import PatchCanvas from './components/PatchCanvas';
import Scope from './components/Scope';
import MacroDial from './components/MacroDial';
import Keyboard from './components/Keyboard';
import Sequencer from './components/Sequencer';

const empty:EngineSnapshot={ready:false,playing:false,step:-1,activeNotes:[],recording:false,recordingSeconds:0,contextState:'not started'};
const errorMessage=(e:unknown)=>e instanceof Error?e.message:String(e);
const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'patchbay';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function initialPatch():Patch {try{return readSharedPatch()||copyPreset(PRESETS[0]);}catch{return copyPreset(PRESETS[0]);}}
export default function App(){
 const [patch,setPatch]=useState<Patch>(initialPatch);const patchRef=useRef(patch);patchRef.current=patch;
 const [engine]=useState(()=>new AudioEngine());const [snapshot,setSnapshot]=useState(empty);const [view,setView]=useState<'play'|'patch'>('play');
 const [selectedId,setSelectedId]=useState<string|null>(patch.modules.find(m=>m.type==='output')?.id||null);const [message,setMessage]=useState('');const [modal,setModal]=useState<'save'|'library'|'share'|'help'|null>(null);const [saveName,setSaveName]=useState('');
 const [saved,setSaved]=useState<SavedPatch[]>([]);const [shareUrl,setShareUrl]=useState('');const [busy,setBusy]=useState(false);const [recordBusy,setRecordBusy]=useState(false);const recordLock=useRef(false);const [recordingUrl,setRecordingUrl]=useState('');const [recordingName,setRecordingName]=useState('');const [midiStatus,setMidiStatus]=useState('Connect MIDI');const [modified,setModified]=useState(false);
 const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const fileInput=useRef<HTMLInputElement>(null);const noteSources=useRef(new Map<number,Set<string>>());const modalRef=useRef<HTMLDialogElement>(null);
 const notify=useCallback((text:string)=>{setMessage(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setMessage(''),6000);},[]);
 const change=useCallback((next:Patch)=>{setPatch(next);setModified(true);},[]);
 const releaseAll=useCallback(()=>{noteSources.current.forEach((_,note)=>engine.noteOff(note));noteSources.current.clear();},[engine]);
 const panic=useCallback(()=>{releaseAll();engine.panic();setSnapshot(engine.getSnapshot());notify('All sound stopped. Ready when you are.');},[engine,notify,releaseAll]);
 useEffect(()=>{engine.setPatch(patch);},[engine,patch]);
 useEffect(()=>{let frame=0,last=0;const tick=(now:number)=>{if(now-last>45){setSnapshot(engine.getSnapshot());last=now;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[engine]);
 useEffect(()=>{try{readSharedPatch();}catch(e){notify(`That shared patch could not be opened. ${errorMessage(e)}`);}const onHash=()=>{try{const next=readSharedPatch();if(next){engine.panic();releaseAll();setPatch(next);setSelectedId(next.modules.find(m=>m.type==='output')?.id||null);setModified(false);notify(`Loaded ${next.name}. Press play when you’re ready.`);}}catch(e){notify(errorMessage(e));}};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[engine,notify,releaseAll]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented){if(modal)setModal(null);else panic();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[modal,panic]);
 useEffect(()=>{const stop=()=>{releaseAll();engine.setPlaying(false);};const visibility=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',stop);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',stop);};},[engine,releaseAll]);
 useEffect(()=>{if(modal)modalRef.current?.showModal();else modalRef.current?.close();},[modal]);
 useEffect(()=>()=>{if(recordingUrl)URL.revokeObjectURL(recordingUrl);},[recordingUrl]);
 const start=async()=>{try{setBusy(true);await engine.start(patchRef.current);setSnapshot(engine.getSnapshot());}catch(e){notify(`Audio could not start. ${errorMessage(e)}`);}finally{setBusy(false);}};
 const togglePlay=async()=>{if(!snapshot.ready||snapshot.contextState!=='running'){await start();return;}if(snapshot.playing){engine.setPlaying(false);releaseAll();}else engine.setPlaying(true);};
 const noteOn=useCallback((note:number,source:string)=>{if(!engine.getSnapshot().ready){notify('Tap Enable audio first, then play any key.');return;}const sources=noteSources.current.get(note)||new Set<string>();if(sources.has(source))return;if(sources.size===0)engine.noteOn(note,.8);sources.add(source);noteSources.current.set(note,sources);},[engine,notify]);
 const noteOff=useCallback((note:number,source:string)=>{const sources=noteSources.current.get(note);if(!sources)return;sources.delete(source);if(sources.size===0){engine.noteOff(note);noteSources.current.delete(note);}},[engine]);
 const loadPatch=(next:Patch)=>{releaseAll();engine.panic();setPatch(copyPreset(next));setSelectedId(next.modules.find(m=>m.type==='output')?.id||null);setModified(false);setModal(null);if(location.hash)history.replaceState(null,'',location.pathname+location.search);notify(`${next.name} is ready. ${next.category==='pad'?'Hold a chord below.':next.category==='lead'?'Play the keys below.':'Press play to begin.'}`);};
 const openLibrary=()=>{try{setSaved(listSavedPatches());setModal('library');}catch(e){notify(errorMessage(e));}};
 const doSave=()=>{try{const next={...patch,name:saveName.trim()||patch.name,id:modified?`user-${crypto.randomUUID().slice(0,12)}`:patch.id};savePatch(next);setPatch(next);setModified(false);setModal(null);notify(`Saved “${next.name}” on this device.`);}catch(e){notify(errorMessage(e));}};
 const openShare=()=>{try{setShareUrl(createShareUrl(patch));setModal('share');}catch(e){notify(errorMessage(e));}};
 const record=async()=>{if(recordLock.current)return;recordLock.current=true;setRecordBusy(true);try{if(snapshot.recording){const result=await engine.stopRecording();const name=`${slug(patch.name)}-${new Date().toISOString().slice(0,10)}.${result.extension}`;setRecordingName(name);setRecordingUrl(URL.createObjectURL(result.blob));notify('Your recording is ready. Listen back or download below.');}else{if(!snapshot.ready)await engine.start(patch);await engine.startRecording();notify('Recording the master output. Press Finish recording when you’re done.');}}catch(e){notify(`Recording: ${errorMessage(e)}`);}finally{recordLock.current=false;setRecordBusy(false);}};
 const midiCleanup=useRef<(()=>void)|null>(null);
 useEffect(()=>()=>midiCleanup.current?.(),[]);
 const connectMidi=async()=>{if(!('requestMIDIAccess' in navigator)){setMidiStatus('MIDI unavailable');notify('This browser does not support Web MIDI. The touch and computer keys still work.');return;}try{
  const access=await (navigator as Navigator & {requestMIDIAccess:()=>Promise<{inputs:Map<string,{id:string;name?:string;onmidimessage:((e:{data:Uint8Array})=>void)|null}>;onstatechange:(()=>void)|null}>}).requestMIDIAccess();
  midiCleanup.current?.(); const attach=()=>{access.inputs.forEach(input=>{input.onmidimessage=e=>{if(!e.data)return;const [status,note,velocity]=e.data;if((status&240)===144&&velocity>0)noteOn(note,`midi-${input.id}`);else if((status&240)===128||((status&240)===144&&velocity===0))noteOff(note,`midi-${input.id}`);else if((status&240)===176&&(note===120||note===123))releaseAll();};});setMidiStatus(access.inputs.size?`${access.inputs.size} MIDI connected`:'MIDI ready · plug in');};attach();access.onstatechange=()=>{releaseAll();attach();};midiCleanup.current=()=>{access.onstatechange=null;access.inputs.forEach(i=>i.onmidimessage=null);};
 }catch(e){setMidiStatus('MIDI not connected');notify(`MIDI access was unavailable. ${errorMessage(e)}`);}};
 const hasSequencer=patch.modules.some(m=>m.type==='sequencer');
 return <div className="app-shell">
  <header className="site-header"><a className="brand" href={import.meta.env.BASE_URL} aria-label="Patchbay home"><AudioLines size={27}/><span>patchbay<span className="brand-dot">.</span></span></a><span className="brand-subtitle">A SMALL UNIVERSE OF SOUND</span><div className="header-actions"><button onClick={openLibrary}><FolderOpen size={16}/><span>My patches</span></button><button onClick={()=>{setSaveName(patch.name);setModal('save');}}><Save size={16}/><span>Save</span></button><button className="share-button" onClick={openShare}><Share2 size={15}/><span>Share patch</span></button><button className="icon-button help-button" aria-label="How to play" onClick={()=>setModal('help')}><CircleHelp size={19}/></button></div></header>
  <main>
   <div className="intro-line"><p>Make a little noise.<span> Find something you love.</span></p><span className="local-badge"><span/> NO ACCOUNT. JUST SOUND.</span></div>
   <nav className="preset-grid" aria-label="Starter patches">{PRESETS.map((p,i)=><button key={p.id} className={`preset-card ${patch.id===p.id?'selected':''}`} onClick={()=>loadPatch(p)} aria-label={`Load ${p.name} ${p.category} patch`} aria-pressed={patch.id===p.id}><span className="preset-number">0{i+1}</span><span className="preset-copy"><strong>{p.name}</strong><small>{p.category==='bass'?'RHYTHMIC BASS':p.category==='pad'?'ATMOSPHERIC PAD':p.category==='lead'?'EXPRESSIVE LEAD':'GENERATIVE AMBIENT'}</small></span><span className={`preset-pattern pattern-${p.category}`} aria-hidden="true">{p.steps.slice(0,12).map((s,j)=><i key={j} style={{height:`${12+(s.note%12)*2}px`,opacity:s.active?1:.22}}/>)}</span><ChevronRight size={16}/></button>)}</nav>
   <section className="instrument" aria-label="Instrument"><div className="instrument-toolbar"><div className="view-tabs" role="tablist" aria-label="Instrument view"><button role="tab" aria-selected={view==='play'} onClick={()=>setView('play')}><Waves size={16}/> Play</button><button role="tab" aria-selected={view==='patch'} onClick={()=>setView('patch')}><SlidersHorizontal size={16}/> Patch<span className="count-badge">{patch.modules.length}</span></button></div><div className="transport-status"><span className={`status-light ${snapshot.playing?'live':''}`}/>{snapshot.playing&&hasSequencer?'IN MOTION':snapshot.ready?'READY TO PLAY':'SOUND IS OFF'}</div><button className="panic-button" onClick={panic} title="Stop all sound · Esc"><Square size={12} fill="currentColor"/> Stop all</button></div>
    <div className="performance-top"><div className="patch-intro"><span className="eyebrow">{patch.category==='custom'?'YOUR INSTRUMENT':`${patch.category.toUpperCase()} / EXPLORATION ${String(PRESETS.findIndex(p=>p.category===patch.category)+1).padStart(2,'0')}`}{modified&&<span className="modified-dot" title="Unsaved changes"/>}</span><h1>{patch.name}</h1><p>{patch.description}</p><div className="main-transport"><button className="start-button" onClick={snapshot.ready?togglePlay:start} disabled={busy}>{snapshot.playing?<Square size={17} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}{busy?'Starting…':!snapshot.ready?'Enable audio':snapshot.playing?'Pause':hasSequencer?'Play sequence':'Play instrument'}</button><span>{!snapshot.ready?<><Headphones size={14}/> Start quiet. Headphones welcome.</>:hasSequencer?`${patch.tempo} BPM · ${patch.steps.filter(s=>s.active).length} active steps`:'Play the keys or hold a chord below'}</span></div></div><Scope engine={engine} patch={patch} selectedId={selectedId} onSelect={setSelectedId} ready={snapshot.ready}/></div>
    <div className="macro-row">{patch.macros.filter(m=>m.mappings.length>0).map((macro,i)=><MacroDial key={macro.id} macro={macro} index={i} patch={patch} onChange={value=>change(applyMacro(patch,macro.id,value))}/>)}</div>
    {view==='patch'?<div className="rack-section"><div className="section-heading"><span className="eyebrow">UNDER THE HOOD</span><p>Every cable is a possibility. Tap an output, then a matching input.</p></div><PatchCanvas patch={patch} selectedId={selectedId} onSelect={setSelectedId} onChange={change} onMessage={notify}/></div>:<Sequencer patch={patch} step={snapshot.step} playing={snapshot.playing} onChange={change}/>}
    <Keyboard resetKey={patch.id} category={patch.category} activeNotes={snapshot.activeNotes} ready={snapshot.ready} onNoteOn={noteOn} onNoteOff={noteOff} onReleaseAll={releaseAll}/>
    <footer className="instrument-footer"><div className="master-control"><Volume2 size={17}/><label htmlFor="master-volume">Master</label><input id="master-volume" aria-label="Master volume" type="range" min="0" max="0.8" step="0.01" value={patch.master} onChange={e=>change({...patch,master:Number(e.target.value)})}/><span>{Math.round(patch.master*100)}%</span></div><button className="midi-button" onClick={connectMidi}><Radio size={15}/>{midiStatus}</button><button className={`record-button ${snapshot.recording?'recording':''}`} onClick={record} disabled={recordBusy}><span className="record-dot"/>{snapshot.recording?`Finish recording · ${Math.floor(snapshot.recordingSeconds/60)}:${String(Math.floor(snapshot.recordingSeconds%60)).padStart(2,'0')}`:'Record audio'}</button></footer>
   </section>
   {recordingUrl&&<section className="recording-result" aria-label="Your recording"><Disc3 size={25}/><div><strong>Your little piece of the universe.</strong><span>{recordingName}</span></div><audio controls src={recordingUrl} aria-label="Play your recording"/><a className="button-link" href={recordingUrl} download={recordingName}><ArrowDownToLine size={16}/> Download audio</a><button className="icon-button" aria-label="Dismiss recording" onClick={()=>setRecordingUrl('')}><X size={18}/></button></section>}
   <div className="page-foot"><span><span className="tiny-logo">⌁</span> Made for happy accidents.</span><button onClick={()=>setModal('help')}>A few things to try <ChevronRight size={14}/></button><span>YOUR BROWSER IS THE INSTRUMENT</span></div>
  </main>
  {snapshot.ready&&<button className="mobile-panic" aria-label="Stop all sound" onClick={panic}><Square size={11} fill="currentColor"/> Stop all</button>}
  {message&&<div className="toast" role="status"><Activity size={17}/><span>{message}</span><button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
  <input ref={fileInput} type="file" accept="application/json,.json" className="sr-only" aria-label="Import patch JSON" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>256*1024)throw new Error('Patch files must be smaller than 256 KiB.');loadPatch(importPatch(await file.text()));notify(`Imported ${file.name}.`);}catch(error){notify(errorMessage(error));}e.target.value='';}}/>
  <dialog ref={modalRef} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><div className="dialog-content"><button className="dialog-close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={21}/></button>
   {modal==='save'&&<><span className="eyebrow">KEEP THE GOOD ONES</span><h2>Save this sound.</h2><p>Keep a copy on this device, exactly as you made it.</p><form onSubmit={e=>{e.preventDefault();doSave();}}><label className="field-label" htmlFor="patch-name">Patch name</label><input id="patch-name" autoFocus maxLength={80} value={saveName} onChange={e=>setSaveName(e.target.value)}/><button className="primary-button" type="submit"><Save size={16}/> Save on this device</button></form><button className="wide-button" onClick={()=>{try{download(new Blob([exportPatch(patch)],{type:'application/json'}),`${slug(patch.name)}.patchbay.json`);notify('Patch JSON exported.');}catch(e){notify(errorMessage(e));}}}><ArrowDownToLine size={16}/> Export a JSON backup</button></>}
   {modal==='library'&&<><span className="eyebrow">YOUR COLLECTION</span><h2>My patches.</h2><p>Saved in this browser. Export a backup to take them with you.</p><div className="saved-list">{saved.length?saved.map(s=><div key={s.id} className="saved-item"><button onClick={()=>loadPatch(s.patch)}><Waves size={19}/><span><strong>{s.name}</strong><small>{new Date(s.savedAt).toLocaleDateString()} · {s.patch.modules.length} modules</small></span><ChevronRight size={18}/></button><button className="icon-button" aria-label={`Delete saved ${s.name}`} onClick={()=>{try{deleteSavedPatch(s.id);setSaved(listSavedPatches());notify('Saved copy removed. Your current instrument is unchanged.');}catch(e){notify(errorMessage(e));}}}><Trash2 size={15}/></button></div>):<div className="empty-collection"><FolderOpen size={30}/><strong>Your first favorite is waiting.</strong><span>Turn a few controls, then tap Save.</span></div>}</div><button className="wide-button" onClick={()=>fileInput.current?.click()}><ArrowUpFromLine size={16}/> Import a patch JSON</button></>}
   {modal==='share'&&<><span className="eyebrow">PASS IT ON</span><h2>A link to your sound.</h2><p>The instrument lives in the link. Open it on another device and pick up where you left off.</p><label className="field-label" htmlFor="share-url">Patch link</label><textarea id="share-url" value={shareUrl} readOnly onFocus={e=>e.target.select()}/><button className="primary-button" onClick={async()=>{try{await navigator.clipboard.writeText(shareUrl);notify('Patch link copied.');}catch{notify('Select and copy the link above. Clipboard access is unavailable.');}}}><Copy size={16}/> Copy link</button>{typeof navigator.share==='function'&&<button className="wide-button" onClick={async()=>{try{await navigator.share({title:`${patch.name} · Patchbay`,url:shareUrl});}catch(e){if((e as Error).name!=='AbortError')notify(errorMessage(e));}}}><Share2 size={16}/> Share to…</button>}<small className="dialog-note">No account or upload. The link contains the patch, not a recording. Links need this app to be hosted to work on another device.</small></>}
   {modal==='help'&&<><span className="eyebrow">FOLLOW YOUR EARS</span><h2>There’s no wrong turn.</h2><div className="help-list"><p><b>01 / Start somewhere.</b>Enable audio, then try the four scenes. Bass and Drift play themselves. Pad and Lead are waiting for your fingers.</p><p><b>02 / Make it yours.</b>Color opens the filter. Bite or Bloom shapes each note. Motion adds movement. Space sends it further away. Drag a dial up or down, or use its arrow keys.</p><p><b>03 / Find a melody.</b>Play the white keys with A S D F G H J K; W E T Y U are the black keys. Hold several keys for a chord. On a phone, use the keys or chord buttons. Edit notes and tap step numbers to change a rhythm.</p><p><b>04 / Follow a cable.</b>Open Patch. Drag module headers to move them and empty canvas to pan. Connect an output to an input of the same type. Select a cable to remove it. Select a sound module to inspect its live signal.</p><p><b>05 / Keep it.</b>Save locally, export JSON, share a patch link, or record the master output. Stop all (or Escape) silences everything. Switching scenes always stops the previous one.</p></div><p className="dialog-note">Use a recent browser. MIDI depends on browser and device support. Playback pauses when this tab goes into the background.</p><button className="primary-button" onClick={()=>setModal(null)}>Let’s play <ChevronRight size={16}/></button></>}
  </div></dialog>
 </div>;
}
